# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Sarah Spear
description: "Full Stack Software Engineer / Techstars mentor / A little short to be a stormtrooper"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
# url: http://sarahspeartheengineer.com
url: https://github.com/ssspear/ssspear.github.io
baseurl: "/"

google_analytics: UA-52446115-1
repo: https://github.com/ssspear/ssspear.github.io

# Author settings
author:
  name: Sarah Spear
  job: Software Engineer
  thumb: /images/author.jpg
  email: sarahspeartheengineer@gmail.com
  url: http://sarahspeartheengineer.com
  github: https://github.com/ssspear
  twitter: https://twitter.com/spearsarah
  linkedin: https://www.linkedin.com/in/spearsarah/

# navbar pages
# navbar:
#   - slug: about
#     title: About
#   - slug: icons
#     title: Icons
#   - slug: blog
#     title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
